title: The Blog of Robert Douglas
description: Build before it is too late. 
author: Douglas Labs
github: https://github.com/realrobertdouglas
about: "Resources for Builders, <a href='/new-post/' style='color:inherit;text-decoration:none'>Thinkers</a>, and Doers"
disqus_shortname: ""
google_analytics: UA-170356546-1

enableTags: true
tagarray: []

collections: {}

social: []

share:
  twitter_username:
  fb_appid: ""

urls:
    - text: Life is short, art is long.
      url: /about/


url: "https://realrobertdouglas.github.io"
baseurl: ""

markdown: kramdown
gems:
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
