title: Robert Douglas
description: Build before it is too late. 
author: Douglas Labs
github: https://github.com/realrobertdouglas
about: Resources for Builders, Thinkers, and Doers
disqus_shortname: realrobertdouglas-github-io
google_analytics: UA-170356546-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social: []

share:
  twitter_username:
  fb_appid:

urls:
    - text: Disclaimer
      url: /about/
    - text: Reports by Project
      url: /projects/

url: "https://realrobertdouglas.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
