title: Life is short, art is long.
description: Build before it is too late. 
author: Douglas Labs
github: https://github.com/realrobertdouglas
about: A collection of resources curated by Robert Douglas, for the review of his peers, use by his followers, and empowerment of his teams.
disqus_shortname: realrobertdouglas-github-io
google_analytics: UA-170356546-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/robertdouglas__"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/robertstewartdouglas/"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/realrobertdouglas"

share:
  twitter_username:
  fb_appid: 

urls:
    - text: About Meee
      url: /about/
    - text: My Projectsss
      url: /projects/
    - text: XML Feeddd
      url: /feed.xml

url: "https://realrobertdouglas.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
